# Generated by Django 5.2.8 on 2026-03-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва моделі')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('image', models.ImageField(blank=True, null=True, upload_to='smartphones/')),
                ('cpu_name', models.CharField(max_length=100, verbose_name='Процесор')),
                ('antutu_score', models.IntegerField(default=0, verbose_name='Бали Antutu')),
                ('battery_mah', models.IntegerField(default=0, verbose_name='Ємність батареї(mAh)')),
                ('ram_gb', models.IntegerField(default=0, verbose_name='RAM (ГБ)')),
                ('release_year', models.IntegerField(default=2024)),
                ('gaming_perf', models.IntegerField(default=0, editable=False)),
                ('battery_life', models.IntegerField(default=0, editable=False)),
                ('total_score', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
