# Generated by Django 5.2.8 on 2026-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='gaming_perf',
            new_name='battery_score',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='battery_life',
            new_name='camera_score',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='display_score',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='main_camera_mp',
            field=models.IntegerField(default=0, verbose_name='кількість мегапікселів камери'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='perf_score',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='screen_hz',
            field=models.IntegerField(default=60, verbose_name='Частота кадрів екрану'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='storage_gb',
            field=models.IntegerField(default=128, verbose_name='Внутрішня память(ГБ)'),
        ),
    ]
