# Generated by Django 5.2.8 on 2026-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rename_gaming_perf_smartphone_battery_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='image',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='image_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Посилання на фото'),
        ),
    ]
