# Generated by Django 5.2.8 on 2026-03-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_smartphone_image_smartphone_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='charge',
            field=models.IntegerField(default=0, verbose_name='швидкість заряджання'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='charge_score',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Посилання на фото'),
        ),
    ]
